version: "3"

services:
  searx:
    image: searx/searx:latest
    restart: unless-stopped
    networks:
      - router
    expose:
      - 8080
    environment:
      - BASE_URL
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=router"
      - "traefik.http.routers.searx.rule=Host(`${TRAEFIK_RULE_HOST}`)"
      - "traefik.http.routers.searx.entrypoints=websecure"
      - "traefik.http.routers.searx.tls.certresolver=letsencrypt"

networks:
  router:
    external: true
