version: '3'

services:
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: vikunja
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: secret
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: jwtsecret
      VIKUNJA_SERVICE_FRONTENDURL: ${TRAEFIK_RULE_HOST}
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - router
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=router"
      - "traefik.http.routers.vikunja-api.rule=Host(`${TRAEFIK_RULE_HOST}`) && (PathPrefix(`/api/v1`) || PathPrefix(`/dav/`) || PathPrefix(`/.well-known/`))"
      - "traefik.http.routers.vikunja-api.entrypoints=websecure"
      - "traefik.http.routers.vikunja-api.tls.certResolver=letsencrypt"
  frontend:
    image: vikunja/frontend
    ports:
      - 8070:80
    environment:
      VIKUNJA_API_URL: ${TRAEFIK_RULE_HOST}
    restart: unless-stopped
    networks:
      - router
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=router"
      - "traefik.http.routers.vikunja-frontend.rule=Host(`${TRAEFIK_RULE_HOST}`)"
      - "traefik.http.routers.vikunja-frontend.entrypoints=websecure"
      - "traefik.http.routers.vikunja-frontend.tls.certResolver=letsencrypt"
networks:
  router:
    external: true
